### ISSUE TITLE
About the language Scala Java, functional programming 

### ISSUE THREAD

**Issue by ypriverol** [BigDataProteomics/bigdataproteomics.github.io#10]
@ruiwanguk I have been reading about functional programming, Scala, Java 8, etc. I know we decided to work with Java but some minor comments should be take into account: 

The aim of the project and the target audience is mainly BigData analyst in the field of proteomics and also developers. The functional programming is really popular in the science and research community due the easy way to implement functions and task in through the data, like R or Python they are really popular to easy interaction between the developers or analysts and the data.  For example, imagine
something like this in the future in the Spark cluster:

scala> import org.bdp.hubble
scala> var spectra = read.mgffile(file.txt)
scala> spectra.filterlowquality()
scala> var PSMs = spectra.searchDataBase(uniprot, MSGGplust)
scala> var proteins = PSMs.proteinInference(psmFDR == 1%)

Looks great? A complete pipeline for protein identification and they can switch the databased Uniprot, or msgplust, and filters etc ... functional programming is great for that and the algorithms will run the the Spark cluster.

**Comment by ruiwanguk** [comment]
@ypriverol I like Scala and I personally is going to invest some time on learning this language. For me and my future career, it is going to be very useful. But a few things we need to consider in the context of this project:

1. To be productive in Scala to be able to program complex algorithms, I would expect to take 5~6 months. 

2. Most of big data projects such as the Hadoop eco-system is based on Java not Scala. 

3. There is no good reason, even for the Spark guys, to use Scala. It is expressive and functional for sure, but my feeling is that this project started a few years ago, at that time, Scala was the only viable option for JVM languages, this is not the case anymore since the introduction of Java 8. 

On the other hand, if we start with Scala, we will learn a lot. Not only in proteomics but also in computer science. 

Here is my suggestion, I suggest we experiment with learning Scala for a month. If it goes well, then we can stick with Scala, but if we feel it is too complex or it is going to take too long to be come productive, then we go back to Java.  What do you think?

**Comment by ypriverol** [comment]
Agree with you, but in any case we should go for a Java 8 approach and the aim for biologist and also developers is to introduce the concept of functionals. Did you see my example, it should be the aim, I saw the presentation of this guys and it is amassing what they are doing. It is possible to implement the algorithms in Java 8 and expose everything in Scala or other functional languages can be another option. As I said this is a future project and we can learn .. I like the idea to start some implementations with Scala and see how it works. Lets keep this issue open.

**Comment by ypriverol** [comment]
Java 8 as core language and think about the possibility to expose using python, Scala

**Comment by ruiwanguk** [comment]
The decision is that we will go for Java 8 for the core libraries, and will offer extensions for Scala, Python and R in the future, where users can interact with our systems using command line.
